#!/bin/sh

#PBS -l mem=16gb,nodes=1:ppn=1,walltime=36:00:00 
#PBS -m abe 
#PBS -M liux1299@umn.edu 
#PBS -q lab

#	The root of where we will work
PROJECT_DIR=${HOME}/Projects/WBDC
#	The capture we are working with
#	And the sample
SAMPLE="WBDC_103"
#	The date of the alignment
ALIGN_DATE="2013-11-20"
#	The programs we are using
SAMTOOLS=${HOME}/Soft/samtools-0.1.19/samtools
PICARD_SORT=${HOME}/Soft/picard-tools-1.103/SortSam.jar
ADDRG=${HOME}/Soft/picard-tools-1.103/AddOrReplaceReadGroups.jar
MARKDUPS=${HOME}/Soft/picard-tools-1.103/MarkDuplicates.jar

ALIGNMENT=${SAMPLE}_${ALIGN_DATE}.sam
#	cd into the directory
cd ${PROJECT_DIR}/${SAMPLE}

#	Use Samtools to trim out the reads we don't care about
#	-f 3 gives us reads mapped in proper pair
#	-F 256 excludes reads not in their primary alignments
$SAMTOOLS view -f 3 -F 256 -bS ${ALIGNMENT} > ${ALIGNMENT/.sam/_trimmed.bam}

#	Picard tools to sort and index
java -Xmx15g -XX:MaxPermSize=10g -jar\
	${PICARD_SORT} \
	INPUT=${ALIGNMENT/.sam/_trimmed.bam} \
	OUTPUT=${ALIGNMENT/.sam/_Sorted.bam} \
	SORT_ORDER=coordinate \
	CREATE_INDEX=true\
	TMP_DIR=${HOME}/Scratch_2/Picard_Tmp

#	Then remove duplicates
java -Xmx15g -XX:MaxPermSize=10g -jar\
	${MARKDUPS} \
	INPUT=${ALIGNMENT/.sam/_Sorted.bam} \
	OUTPUT=${ALIGNMENT/.sam/_NoDups.bam} \
	METRICS_FILE=${ALIGNMENT/.sam/_Metrics.txt}\
	REMOVE_DUPLICATES=true\
	CREATE_INDEX=true\
	TMP_DIR=${HOME}/Scratch/Picard_Tmp\
	MAX_RECORDS_IN_RAM=50000

#	Then add read groups
java -Xmx15g -XX:MaxPermSize=10g -jar\
	${ADDRG} \
	INPUT=${ALIGNMENT/.sam/_NoDups.bam} \
	OUTPUT=${ALIGNMENT/.sam/_Finished.bam} \
	RGID=${SAMPLE}\
	RGPL=Illumina\
	RGPU=${SAMPLE}\
	RGSM=${SAMPLE}\
	RGLB=${SAMPLE}\
	TMP_DIR=${HOME}/Scratch/Picard_Tmp\
	CREATE_INDEX=True

#	Get rid of everything except the finihed BAM file
#find . -type f -not -name '*Finished*' | xargs rm
